version: '3.8'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    stdin_open: true
    command: npm start
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './frontend:/frontend'
      - './frontend/node_modules:/frontend/node_modules'
